spring.application.name=order-fulfillment-service
server.port=8081

# Tell the client where the server is
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Force the use of IP instead of the LTIN hostname
eureka.instance.prefer-ip-address=true

# Explicitly tell it WHICH IP to use (localhost for your dev environment)
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.ip-address}:${server.port}

spring.kafka.bootstrap-servers=127.0.0.1:9092

# Resilience4j Circuit Breaker Configuration
# 1. Give the circuit breaker a name (we'll use 'inventory') and set the sample size
resilience4j.circuitbreaker.instances.inventory.sliding-window-size=5

# 2. If 50% of the last 5 calls fail, OPEN the circuit
resilience4j.circuitbreaker.instances.inventory.failure-rate-threshold=50

# 3. Wait 10 seconds before letting 1 test request through (HALF-OPEN state)
resilience4j.circuitbreaker.instances.inventory.wait-duration-in-open-state=10s
