spring.application.name=order-fulfillment-service
server.port=8081

# Tell the client where the server is
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Force the use of IP instead of the LTIN hostname
eureka.instance.prefer-ip-address=true

# Explicitly tell it WHICH IP to use (localhost for your dev environment)
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.ip-address}:${server.port}