spring.application.name=inventory-service
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.ip-address}:${server.port}

# 1. Point to the local broker
spring.kafka.bootstrap-servers=127.0.0.1:9092

# 2. Define the team name (matches your @KafkaListener)
spring.kafka.consumer.group-id=inventory-group

# 3. Tell it to always read unread messages from the beginning if it connects late
spring.kafka.consumer.auto-offset-reset=earliest

# 4. Explicitly tell it how to translate the byte payload back into Java Strings
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer